project:
  type: website
  output-dir: _site
  resources:
    - software/*.svg

website:
  title: "Nick Alger"
  description: "Research, publications, and software."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: notes.qmd
        text: Notes

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    toc: false
    smooth-scroll: true
